// Deterministic standalone driver for the fuzz target — no libFuzzer runtime needed. Feeds
// many generated byte buffers (a fixed-seed LCG: deterministic, no RNG/wall-clock dependence,
// C-4.6) including the bytes that stress JSON escaping (quotes, backslashes, control + high
// bytes). Runs under ASan/UBSan so any OOB/UB in the target fails the CTest.
#include <cstddef>
#include <cstdint>
#include <vector>

extern "C" int LLVMFuzzerTestOneInput(const std::uint8_t* data, std::size_t size);

int main() {
    std::uint64_t state = 0x9e3779b97f4a7c15ull;  // fixed seed
    auto next = [&state]() -> std::uint32_t {
        state = state * 6364136223846793005ull + 1442695040888963407ull;
        return static_cast<std::uint32_t>(state >> 33);
    };

    constexpr int kIterations = 200000;
    std::vector<std::uint8_t> buf;
    for (int i = 0; i < kIterations; ++i) {
        const std::size_t len = next() % 257;  // 0..256 bytes
        buf.resize(len);
        for (std::size_t j = 0; j < len; ++j) {
            const std::uint32_t r = next();
            // Bias toward JSON-significant bytes a quarter of the time.
            if ((r & 0x3u) == 0) {
                static const char hot[] = {'"', '\\', '\n', '\r', '\t', '\b', '\f', '{', '}'};
                buf[j] = static_cast<std::uint8_t>(hot[r % sizeof(hot)]);
            } else {
                buf[j] = static_cast<std::uint8_t>(r & 0xffu);
            }
        }
        if (LLVMFuzzerTestOneInput(buf.data(), buf.size()) != 0) return 1;
    }
    return 0;
}
