#!/usr/bin/env python3
"""
Compile anchored system prompt from versioned governance files (Phase 0).

Concatenates binding docs so invariants are not left in mutable conversation state.
"""

from __future__ import annotations

import argparse
from pathlib import Path

DEFAULT_SOURCES = [
    "docs/handoff.md",
    "docs/architecture/CONSTRAINTS.md",
    "docs/architecture/ARCHITECTURE.md",
    "docs/adr/README.md",
    "docs/governance/autonomation/AUTONOMATION_SYSTEM_ARCHITECTURE_RULES.md",
    "docs/superpowers/plans/2026-06-11-agentic-work-memory-hardening.md",
]

SECTION_RULES = """## Binding rules (§0 excerpt)

| ID | Rule |
|---|---|
| C-5.1 | Implementation requires recorded authorization in handoff.md |
| C-5.2 | On drift: STOP, file docs/drift/DRIFT-YYYYMMDD-<slug>.md, request approval |
| C-5.3 | Knowledge first, code second |
| C-5.4 | No placeholders in production paths; failing tests never merge |
| C-5.5 | Monorepo top level: apps/ libs/ research/ docs/ tools/ |
| C-5.6 | Every work session updates docs/handoff.md |
| AutonomAtIon 1–5 | Domain isolation; CAD thread safety; transactions; no API hallucinations; preserve guards/audit |
"""


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def compile_prompt(root: Path, sources: list[str]) -> str:
    parts = [
        "# InGENeer anchored prompt",
        "",
        "Generated by tools/agentic/compile_prompt.py — do not edit by hand.",
        "",
        SECTION_RULES,
        "",
    ]
    for rel in sources:
        path = root / rel
        if not path.is_file():
            raise FileNotFoundError(f"missing source: {rel}")
        parts.append(f"---\n\n## Source: {rel}\n\n")
        parts.append(path.read_text(encoding="utf-8"))
        parts.append("\n")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile anchored agent prompt")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="write prompt to file (default: stdout)",
    )
    parser.add_argument(
        "--source",
        action="append",
        dest="sources",
        help="additional source file (repeatable); defaults to governance bundle",
    )
    args = parser.parse_args()
    root = repo_root()
    sources = args.sources if args.sources else DEFAULT_SOURCES
    text = compile_prompt(root, sources)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
