// Deterministic standalone driver for the TIN fuzz target — no libFuzzer runtime needed
// (same pattern as libs/audit_core/fuzz/standalone_main.cpp). Feeds generated byte
// buffers from a fixed-seed LCG (deterministic, no RNG/wall-clock dependence, C-4.6) into
// LLVMFuzzerTestOneInput; the target itself asserts the full TIN invariant set after
// every op. Runs under ASan/UBSan so any OOB/UB fails the CTest.
//
// Iteration count defaults to 200000 (the Phase 6.5 gate); argv[1] overrides for local
// deep runs.
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>

extern "C" int LLVMFuzzerTestOneInput(const std::uint8_t* data, std::size_t size);

int main(int argc, char** argv) {
    int iterations = 200000;
    if (argc > 1) iterations = std::atoi(argv[1]);

    std::uint64_t state = 0x9e3779b97f4a7c15ull;  // fixed seed
    auto next = [&state]() -> std::uint32_t {
        state = state * 6364136223846793005ull + 1442695040888963407ull;
        return static_cast<std::uint32_t>(state >> 33);
    };

    std::vector<std::uint8_t> buf;
    for (int i = 0; i < iterations; ++i) {
        const std::size_t len = next() % 257;  // 0..256 bytes
        buf.resize(len);
        for (std::size_t j = 0; j < len; ++j) {
            buf[j] = static_cast<std::uint8_t>(next() & 0xffu);
        }
        if (LLVMFuzzerTestOneInput(buf.data(), buf.size()) != 0) return 1;
    }
    std::printf("fuzz_tin standalone: %d iterations clean\n", iterations);
    return 0;
}
